version: '3'
services:
  gateway:
    container_name: api-gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - "pdf-service"
      - "storage-service"
    networks:
      - mynet
  pdf-service:
    container_name: pdf-service
    build:
      context: './pdf-service'
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8001"
    networks:
      - mynet
  storage-service:
    container_name: storage-service
    build:
      context: './storage-service'
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8002:8002"
    networks:
      - mynet
    depends_on:
      - pdf-service
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default